### ISSUE TITLE
Getting uncaught (in promise) error using Angular2-cli 

### ISSUE THREAD

**Issue by estradamarkie** [makinacorpus/angular2-schema-form#30]
I followed the instruction how to implement it, although I'm not doing it on `app.component.ts` I'm implementing it on the actual component which is going to use this.

I'm not sure about the main.browser.ts, but I created that and pasted the code for this file but it still giving me this big error.

Can you shed a light on this error please

`Error: Uncaught (in promise): Error: Error in ./InterfaceComponent class InterfaceComponent - inline template:94:19 caused by: Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at FormComponent.ngOnChanges (http://localhost:3000/main.bundle.js:62933:26)
    at Wrapper_FormComponent.detectChangesInInputProps (/SchemaFormModule/FormComponent/wrapper.ngfactory.js:54:18)
    at _View_InterfaceComponent0.detectChangesInternal (/AppModule/InterfaceComponent/component.ngfactory.js:522:29)
    at _View_InterfaceComponent0.AppView.detectChanges (http://localhost:3000/main.bundle.js:58615:14)
    at _View_InterfaceComponent0.DebugAppView.detectChanges (http://localhost:3000/main.bundle.js:58720:44)
    at _View_InterfaceComponent_Host0.AppView.detectViewChildrenChanges (http://localhost:3000/main.bundle.js:58641:19)
    at _View_InterfaceComponent_Host0.detectChangesInternal (/AppModule/InterfaceComponent/host.ngfactory.js:33:8)
    at _View_InterfaceComponent_Host0.AppView.detectChanges (http://localhost:3000/main.bundle.js:58615:14)
    at _View_InterfaceComponent_Host0.DebugAppView.detectChanges (http://localhost:3000/main.bundle.js:58720:44)
    at ViewRef_.detectChanges (http://localhost:3000/main.bundle.js:41840:20)
    at resolvePromise (http://localhost:3000/main.bundle.js:81977:31)
    at http://localhost:3000/main.bundle.js:81954:13
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:81741:26)
    at Object.onInvoke (http://localhost:3000/main.bundle.js:28680:37)
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:81740:32)
    at Zone.run (http://localhost:3000/main.bundle.js:81623:43)
    at http://localhost:3000/main.bundle.js:82011:57
    at ZoneDelegate.invokeTask (http://localhost:3000/main.bundle.js:81774:35)
    at Object.onInvokeTask (http://localhost:3000/main.bundle.js:28671:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/main.bundle.js:81773:40)`

JSON schema looks like this:
`{
  "type": "object",
  "properties": {
    "Name": {
      "type": "string"
    },
    "Number": {
      "format": "int32",
      "type": "integer"
    },
    "PointInTime": {
      "format": "date-time",
      "type": "string"
    },
    "Url": {
      "type": "string"
    },
    "Children": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ChildName": {
            "type": "string"
          },
          "ChildNumber": {
            "format": "int32",
            "type": "integer"
          },
          "ChildPointInTime": {
            "format": "date-time",
            "type": "string"
          },
          "CustomData": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object"
              }
            }
          }
        }
      }
    },
    "CustomData": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "object"
        }
      }
    }
  }
}`

**Comment by estradamarkie** [comment]
Nevermind, I think I just need to add this `"$schema": "http://json-schema.org/draft-04/hyper-schema#",` in my JSON and it works fine
